import { prisma } from '@/lib/db'
import { verifyToken } from '@/lib/jwt'
import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  // Verify authentication and role (ADMIN or SUPERVISOR)
  const cookieHeader = request.headers.get('cookie') || ''
  let token: string | undefined = undefined
  const cookieList = cookieHeader.split(';')
  for (const cookie of cookieList) {
    const [name, val] = cookie.trim().split('=')
    if (name === 'token') {
      token = val
      break
    }
  }

  if (!token) {
    return NextResponse.json({ error: 'Chưa đăng nhập' }, { status: 401 })
  }

  const payload = await verifyToken(token)
  if (!payload) {
    return NextResponse.json({ error: 'Phiên làm việc hết hạn hoặc không hợp lệ' }, { status: 401 })
  }

  const hasPermission = payload.role === 'ADMIN' || payload.role === 'SUPERVISOR' || (payload.permissions || []).includes('admin:batch')
  if (!hasPermission) {
    return NextResponse.json({ error: 'Không có quyền thực hiện thao tác này' }, { status: 403 })
  }

  try {
    const body = await request.json()
    const { linenCirculationId, discardQuantity, action, recycledQuantity } = body

    if (!linenCirculationId || !discardQuantity || !action) {
      return NextResponse.json({ error: 'Thiếu thông tin bắt buộc' }, { status: 400 })
    }

    if (Number(discardQuantity) <= 0) {
      return NextResponse.json({ error: 'Số lượng báo hỏng phải lớn hơn 0' }, { status: 400 })
    }

    if (action === 'RECYCLE' && (recycledQuantity === undefined || Number(recycledQuantity) <= 0)) {
      return NextResponse.json({ error: 'Số lượng vỏ gối thu hồi tái chế không hợp lệ' }, { status: 400 })
    }

    const result = await prisma.$transaction(async (tx) => {
      // 1. Fetch source circulation
      const circulation = await tx.linenCirculation.findUnique({
        where: { id: linenCirculationId },
        include: { linenType: true }
      })

      if (!circulation) {
        throw new Error('Lô đồ vải lưu thông không tồn tại')
      }

      if (circulation.activeQuantity < Number(discardQuantity)) {
        throw new Error(`Số lượng báo hỏng vượt quá lượng lưu hành còn lại (${circulation.activeQuantity})`)
      }

      const isDrap = circulation.linenType.name.toLowerCase().includes('drap') ||
                    circulation.linenType.name.toLowerCase().includes('ga trải') ||
                    circulation.linenType.name.toLowerCase().includes('ga giường')

      if (action === 'RECYCLE' && !isDrap) {
        throw new Error('Chỉ có thể tái chế từ các loại Drap/Ga trải giường')
      }

      // 2. Decrement activeQuantity and increment discardedQuantity in circulation
      const updatedCirculation = await tx.linenCirculation.update({
        where: { id: linenCirculationId },
        data: {
          activeQuantity: { decrement: Number(discardQuantity) },
          discardedQuantity: { increment: Number(discardQuantity) },
        }
      })

      // 3. Create LinenDiscardLog
      const reason = action === 'RECYCLE' 
        ? `Tái chế thành Vỏ gối (Thu hồi: ${recycledQuantity} cái)`
        : 'Báo hỏng thông thường'

      const discardLog = await tx.linenDiscardLog.create({
        data: {
          linenCirculationId,
          quantity: Number(discardQuantity),
          reason,
        }
      })

      // 4. Create target batch for Pillowcases (Vỏ gối) if recycling
      let newBatch = null
      if (action === 'RECYCLE') {
        // Find or create "Vỏ gối" LinenType
        let targetLinenType = await tx.linenType.findFirst({
          where: { name: { equals: 'Vỏ gối', mode: 'insensitive' } }
        })

        if (!targetLinenType) {
          targetLinenType = await tx.linenType.create({
            data: {
              name: 'Vỏ gối',
              unit: 'Cái'
            }
          })
        }

        // Generate autogenerated batch code
        const todayStr = new Date().toISOString().slice(0, 10).replace(/-/g, '')
        const batchCode = `RECYCLE-${todayStr}`

        newBatch = await tx.batch.create({
          data: {
            code: batchCode,
            linenTypeId: targetLinenType.id,
            totalQuantity: Number(recycledQuantity),
            remainingQuantity: Number(recycledQuantity),
            importedAt: new Date(),
          }
        })
      }

      return { updatedCirculation, discardLog, newBatch }
    })

    return NextResponse.json(result, { status: 201 })
  } catch (error: any) {
    console.error('POST inventory recycle error:', error)
    return NextResponse.json({ error: error.message || 'Lỗi hệ thống khi báo hỏng/tái chế' }, { status: 400 })
  }
}
